# Generated by Django 5.0.3 on 2024-03-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_request_status_alter_request_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='message',
            new_name='description',
        ),
        migrations.AddField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
